export const CATEGORY_NAMES: Record<string, { es: string; en: string; fr: string; icon: string }> = {
  restaurant: { es: 'Restaurantes', en: 'Restaurants', fr: 'Restaurants', icon: 'Utensils' },
  cafe: { es: 'Cafeterías', en: 'Cafés', fr: 'Cafés', icon: 'Coffee' },
  tourist_attraction: { es: 'Lugares de interés', en: 'Tourist Attractions', fr: 'Attractions touristiques', icon: 'Camera' },
  park: { es: 'Parques y naturaleza', en: 'Parks & Nature', fr: 'Parcs & Nature', icon: 'Trees' },
  beach: { es: 'Playas', en: 'Beaches', fr: 'Plages', icon: 'Waves' },
  shopping_mall: { es: 'Compras', en: 'Shopping', fr: 'Shopping', icon: 'ShoppingBag' },
  museum: { es: 'Museos', en: 'Museums', fr: 'Musées', icon: 'Landmark' },
  bar: { es: 'Bares', en: 'Bars', fr: 'Bars', icon: 'Wine' },
  pharmacy: { es: 'Farmacias', en: 'Pharmacies', fr: 'Pharmacies', icon: 'Pill' },
  hospital: { es: 'Hospitales', en: 'Hospitals', fr: 'Hôpitaux', icon: 'Hospital' },
  supermarket: { es: 'Supermercados', en: 'Supermarkets', fr: 'Supermarchés', icon: 'ShoppingCart' },
  gym: { es: 'Gimnasios', en: 'Gyms', fr: 'Salles de sport', icon: 'Dumbbell' },
  // Missing categories that were showing raw IDs
  ice_cream: { es: 'Heladerías', en: 'Ice Cream', fr: 'Glaciers', icon: 'IceCream' },
  pub: { es: 'Pubs', en: 'Pubs', fr: 'Pubs', icon: 'Beer' },
  club: { es: 'Discotecas', en: 'Clubs', fr: 'Clubs', icon: 'Music' },
  grill: { es: 'Asadores', en: 'Grills', fr: 'Grillades', icon: 'Flame' },
  cathedral: { es: 'Catedrales e iglesias', en: 'Cathedrals & Churches', fr: 'Cathédrales & Églises', icon: 'Church' },
  // Extra common categories
  bakery: { es: 'Panaderías', en: 'Bakeries', fr: 'Boulangeries', icon: 'Croissant' },
  nightlife: { es: 'Vida nocturna', en: 'Nightlife', fr: 'Vie nocturne', icon: 'Moon' },
  shopping: { es: 'Tiendas', en: 'Shops', fr: 'Boutiques', icon: 'ShoppingBag' },
  spa: { es: 'Spas y bienestar', en: 'Spas & Wellness', fr: 'Spas & Bien-être', icon: 'Sparkles' },
  parking: { es: 'Aparcamientos', en: 'Parking', fr: 'Parkings', icon: 'Car' },
  atm: { es: 'Cajeros automáticos', en: 'ATMs', fr: 'Distributeurs', icon: 'Banknote' },
  laundry: { es: 'Lavanderías', en: 'Laundry', fr: 'Laveries', icon: 'WashingMachine' },
  market: { es: 'Mercados', en: 'Markets', fr: 'Marchés', icon: 'Store' },
  viewpoint: { es: 'Miradores', en: 'Viewpoints', fr: 'Belvédères', icon: 'Eye' },
  monument: { es: 'Monumentos', en: 'Monuments', fr: 'Monuments', icon: 'Landmark' },
  art_gallery: { es: 'Galerías de arte', en: 'Art Galleries', fr: 'Galeries d\'art', icon: 'Palette' },
}
