[build]
builder = "nixpacks"
buildCommand = "cd apps/web && npm install && npm run build"

[deploy]
startCommand = "cd apps/web && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { NODE_ENV = "production" }

[[deploy.healthCheckPath]]
path = "/"