/**
 * Recommendation category definitions.
 * Maps each category to its group, display metadata, field labels and tags.
 */

export type DataSource = 'OSM' | 'GOOGLE'

export interface CategoryConfig {
  id: string
  label: string
  icon: string
  group: string
  source: DataSource
  radius: number
  maxResults: number
  defaultEnabled: boolean
  googleType?: string
  osmTags?: Record<string, string | string[]>
  searchMode?: 'nearby' | 'text' | 'ai_curated'
  textQuery?: string
  aiPrompt?: string
  fetchDetails?: boolean
  /** Label for the "highlight" field. Undefined = hide the field */
  highlightLabel?: string
  highlightPlaceholder?: string
  /** Label for the "externalUrl" field. Undefined = hide the field */
  externalUrlLabel?: string
  externalUrlPlaceholder?: string
  /** Tags available for this category */
  tags?: string[]
}

export interface CategoryGroup {
  id: string
  label: string
  emoji: string
}

export const CATEGORY_GROUPS: CategoryGroup[] = [
  { id: 'gastronomy', label: 'Gastronomía',            emoji: '🍽️' },
  { id: 'cafe',       label: 'Café & Brunch',           emoji: '☕' },
  { id: 'nightlife',  label: 'Bares & Noche',           emoji: '🍸' },
  { id: 'heritage',   label: 'Monumentos & Patrimonio', emoji: '🏛️' },
  { id: 'culture',    label: 'Cultura & Arte',           emoji: '🎨' },
  { id: 'nature',     label: 'Naturaleza',               emoji: '🌿' },
  { id: 'urban',      label: 'Vida urbana',              emoji: '🏙️' },
  { id: 'activities', label: 'Actividades',              emoji: '🎯' },
  { id: 'shopping',   label: 'Compras',                  emoji: '🛍️' },
  { id: 'family',     label: 'Familia',                  emoji: '👨‍👩‍👧' },
  { id: 'services',   label: 'Servicios',                emoji: '🔧' },
]

export const CATEGORIES: CategoryConfig[] = [

  // ═══════════════════════════════════════════
  // 🍽️ GASTRONOMÍA
  // ═══════════════════════════════════════════
  {
    id: 'restaurant',
    label: 'Restaurante',
    icon: 'UtensilsCrossed',
    group: 'gastronomy',
    source: 'GOOGLE',
    radius: 5000,
    maxResults: 8,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Los 8 mejores restaurantes de {city}. Mezcla alta cocina, locales populares auténticos y buena relación calidad-precio.',
    fetchDetails: true,
    highlightLabel: 'Plato estrella',
    highlightPlaceholder: 'Ej: El arroz a banda, la lubina a la sal',
    externalUrlLabel: 'Reservar mesa',
    externalUrlPlaceholder: 'https://www.thefork.es/...',
    tags: ['terraza', 'vistas', 'romántico', 'vegetariano', 'sin_gluten', 'sin_reserva', 'económico', 'para_grupos', 'local_típico', 'estrella_michelin'],
  },
  {
    id: 'local_cuisine',
    label: 'Cocina local / típica',
    icon: 'ChefHat',
    group: 'gastronomy',
    source: 'GOOGLE',
    radius: 5000,
    maxResults: 6,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Los 6 mejores restaurantes de cocina típica y tradicional de {city}. Solo locales auténticos, sin turismo masificado.',
    fetchDetails: true,
    highlightLabel: 'Plato típico imprescindible',
    highlightPlaceholder: 'Ej: Pide el cocido madrileño del mediodía',
    externalUrlLabel: 'Reservar mesa',
    externalUrlPlaceholder: 'https://...',
    tags: ['local_típico', 'sin_reserva', 'económico', 'solo_efectivo', 'mercado', 'generoso'],
  },
  {
    id: 'seafood',
    label: 'Marisquería / pescadería',
    icon: 'Fish',
    group: 'gastronomy',
    source: 'GOOGLE',
    radius: 5000,
    maxResults: 5,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Las 5 mejores marisquerías y restaurantes de pescado fresco de {city}.',
    fetchDetails: true,
    highlightLabel: 'Qué pedir',
    highlightPlaceholder: 'Ej: Las gambas rojas y el langostino al ajillo',
    externalUrlLabel: 'Reservar mesa',
    externalUrlPlaceholder: 'https://...',
    tags: ['fresco_del_día', 'terraza', 'romántico', 'sin_reserva', 'económico'],
  },
  {
    id: 'grill',
    label: 'Asador / parrilla',
    icon: 'Flame',
    group: 'gastronomy',
    source: 'GOOGLE',
    radius: 5000,
    maxResults: 5,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Los 5 mejores asadores, parrillas y restaurantes de carne a la brasa de {city}.',
    fetchDetails: true,
    highlightLabel: 'Corte recomendado',
    highlightPlaceholder: 'Ej: El chuletón de buey, mínimo 1kg para dos',
    externalUrlLabel: 'Reservar mesa',
    externalUrlPlaceholder: 'https://...',
    tags: ['para_grupos', 'romántico', 'reserva_recomendada', 'económico'],
  },
  {
    id: 'vegetarian',
    label: 'Vegetariano / vegano',
    icon: 'Leaf',
    group: 'gastronomy',
    source: 'GOOGLE',
    radius: 5000,
    maxResults: 5,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Los 5 mejores restaurantes vegetarianos y veganos de {city}.',
    fetchDetails: true,
    highlightLabel: 'Plato estrella',
    highlightPlaceholder: 'Ej: El bowl de acaí y la pizza de coliflor',
    externalUrlLabel: 'Reservar mesa',
    externalUrlPlaceholder: 'https://...',
    tags: ['100%_vegano', 'sin_gluten', 'orgánico', 'económico', 'terraza'],
  },
  {
    id: 'street_food',
    label: 'Street food / mercado gastronómico',
    icon: 'Store',
    group: 'gastronomy',
    source: 'GOOGLE',
    radius: 5000,
    maxResults: 5,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Los 5 mejores mercados gastronómicos, food trucks y puestos de street food de {city}.',
    fetchDetails: true,
    highlightLabel: 'Qué no perderte',
    highlightPlaceholder: 'Ej: Los takoyaki del puesto de la entrada',
    externalUrlLabel: 'Web del mercado',
    externalUrlPlaceholder: 'https://...',
    tags: ['económico', 'local_típico', 'sin_reserva', 'para_familias', 'ambiente'],
  },
  {
    id: 'ice_cream',
    label: 'Heladería / pastelería',
    icon: 'IceCream',
    group: 'gastronomy',
    source: 'GOOGLE',
    radius: 3000,
    maxResults: 4,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Las 4 mejores heladerías artesanales y pastelerías de {city}.',
    fetchDetails: true,
    highlightLabel: 'Sabor / especialidad',
    highlightPlaceholder: 'Ej: El helado de turrón y la ensaimada rellena',
    tags: ['artesanal', 'sin_gluten', 'para_niños', 'económico'],
  },
  {
    id: 'bakery',
    label: 'Panadería / desayuno',
    icon: 'Croissant',
    group: 'gastronomy',
    source: 'GOOGLE',
    radius: 2000,
    maxResults: 4,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Las 4 mejores panaderías artesanales y lugares de desayuno de {city}.',
    fetchDetails: true,
    highlightLabel: 'Qué pedir',
    highlightPlaceholder: 'Ej: El pan de masa madre y el croissant de mantequilla',
    tags: ['artesanal', 'sin_gluten', 'abre_temprano', 'económico'],
  },

  // ═══════════════════════════════════════════
  // ☕ CAFÉ & BRUNCH
  // ═══════════════════════════════════════════
  {
    id: 'cafe',
    label: 'Cafetería',
    icon: 'Coffee',
    group: 'cafe',
    source: 'GOOGLE',
    radius: 3000,
    maxResults: 5,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Las 5 mejores cafeterías de especialidad y con buen ambiente de {city}.',
    fetchDetails: true,
    highlightLabel: 'Especialidad',
    highlightPlaceholder: 'Ej: El cold brew y el cortado sobre hielo',
    tags: ['especialidad', 'trabaja_desde_aquí', 'wifi', 'terraza', 'tranquilo', 'instagram'],
  },
  {
    id: 'brunch',
    label: 'Brunch',
    icon: 'Egg',
    group: 'cafe',
    source: 'GOOGLE',
    radius: 3000,
    maxResults: 5,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Los 5 mejores brunch spots y cafeterías para desayunar bien en {city}.',
    fetchDetails: true,
    highlightLabel: 'Plato estrella',
    highlightPlaceholder: 'Ej: Los eggs benedict y el smoothie bowl',
    externalUrlLabel: 'Reservar',
    externalUrlPlaceholder: 'https://...',
    tags: ['sin_reserva', 'terraza', 'instagram', 'vegan_friendly', 'sin_gluten'],
  },
  {
    id: 'tea_bar',
    label: 'Tetería / matcha bar',
    icon: 'LeafyGreen',
    group: 'cafe',
    source: 'GOOGLE',
    radius: 3000,
    maxResults: 4,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Las 4 mejores teterías, matcha bars y locales de té de especialidad en {city}.',
    fetchDetails: true,
    highlightLabel: 'Qué tomar',
    highlightPlaceholder: 'Ej: El matcha latte ceremonial con leche de avena',
    tags: ['tranquilo', 'instagram', 'trabaja_desde_aquí', 'wifi'],
  },

  // ═══════════════════════════════════════════
  // 🍸 BARES & NOCHE
  // ═══════════════════════════════════════════
  {
    id: 'cocktail_bar',
    label: 'Bar de cócteles',
    icon: 'GlassWater',
    group: 'nightlife',
    source: 'GOOGLE',
    radius: 3000,
    maxResults: 5,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Los 5 mejores bares de cócteles de {city}. Incluye bares speakeasy, rooftops y locales con carta creativa.',
    fetchDetails: true,
    highlightLabel: 'Cóctel que no perderse',
    highlightPlaceholder: 'Ej: El Negroni envejecido en barrica o el gin tonic de la casa',
    tags: ['rooftop', 'terraza', 'música_en_vivo', 'reserva_recomendada', 'romántico', 'dress_code'],
  },
  {
    id: 'wine_bar',
    label: 'Bar de vinos / bodega',
    icon: 'Wine',
    group: 'nightlife',
    source: 'GOOGLE',
    radius: 3000,
    maxResults: 5,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Los 5 mejores bares de vinos, enotecas y bodegas urbanas de {city}.',
    fetchDetails: true,
    highlightLabel: 'Vino / maridaje recomendado',
    highlightPlaceholder: 'Ej: Pide el monastrell de la DO Alicante con la tabla de ibéricos',
    tags: ['maridaje', 'tapas', 'romántico', 'terraza', 'económico'],
  },
  {
    id: 'tapas_bar',
    label: 'Bar de tapas / pintxos',
    icon: 'Utensils',
    group: 'nightlife',
    source: 'GOOGLE',
    radius: 3000,
    maxResults: 6,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Los 6 mejores bares de tapas, pintxos y raciones de {city}. Solo locales auténticos.',
    fetchDetails: true,
    highlightLabel: 'Tapa imprescindible',
    highlightPlaceholder: 'Ej: La croqueta de jamón y el pulpo a la gallega',
    tags: ['sin_reserva', 'económico', 'local_típico', 'ambiente', 'para_grupos'],
  },
  {
    id: 'rooftop',
    label: 'Rooftop bar / terraza',
    icon: 'Building2',
    group: 'nightlife',
    source: 'GOOGLE',
    radius: 5000,
    maxResults: 5,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Los 5 mejores rooftop bars y terrazas con vistas de {city}.',
    fetchDetails: true,
    highlightLabel: 'Mejor hora para ir',
    highlightPlaceholder: 'Ej: Al atardecer, llega pronto porque se llena rápido',
    externalUrlLabel: 'Reservar',
    externalUrlPlaceholder: 'https://...',
    tags: ['vistas', 'puesta_de_sol', 'reserva_recomendada', 'romántico', 'dress_code', 'instagram'],
  },
  {
    id: 'pub',
    label: 'Pub / cervecería',
    icon: 'Beer',
    group: 'nightlife',
    source: 'GOOGLE',
    radius: 3000,
    maxResults: 5,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Los 5 mejores pubs, cervecerías artesanales y bares con ambiente de {city}.',
    fetchDetails: true,
    highlightLabel: 'Cerveza / bebida estrella',
    highlightPlaceholder: 'Ej: La IPA artesanal de barril o el stout de temporada',
    tags: ['artesanal', 'deporte_en_pantalla', 'música_en_vivo', 'terraza', 'sin_reserva'],
  },
  {
    id: 'club',
    label: 'Discoteca / club',
    icon: 'Music',
    group: 'nightlife',
    source: 'GOOGLE',
    radius: 5000,
    maxResults: 4,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Los 4 mejores clubs nocturnos y discotecas de {city}.',
    fetchDetails: true,
    highlightLabel: 'Noche / ambiente',
    highlightPlaceholder: 'Ej: Los jueves de house electrónico, entrada gratis antes de la 1',
    externalUrlLabel: 'Entradas / lista',
    externalUrlPlaceholder: 'https://...',
    tags: ['dress_code', 'lista_de_invitados', 'terraza', 'reserva_recomendada'],
  },

  // ═══════════════════════════════════════════
  // 🏛️ MONUMENTOS & PATRIMONIO
  // ═══════════════════════════════════════════
  {
    id: 'cathedral',
    label: 'Catedral / iglesia / templo',
    icon: 'Church',
    group: 'heritage',
    source: 'GOOGLE',
    radius: 10000,
    maxResults: 5,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Las 5 catedrales, iglesias, mezquitas y templos más importantes de {city}.',
    fetchDetails: true,
    highlightLabel: 'No te pierdas',
    highlightPlaceholder: 'Ej: Sube a la torre sur para ver la ciudad al atardecer',
    externalUrlLabel: 'Comprar entradas',
    externalUrlPlaceholder: 'https://...',
    tags: ['gratis', 'entrada_de_pago', 'visita_guiada', 'audioguía', 'accesible', 'patrimonio_unesco'],
  },
  {
    id: 'castle',
    label: 'Castillo / fortaleza',
    icon: 'Castle',
    group: 'heritage',
    source: 'GOOGLE',
    radius: 15000,
    maxResults: 4,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Los 4 castillos y fortalezas más importantes de {city} y alrededores.',
    fetchDetails: true,
    highlightLabel: 'No te pierdas',
    highlightPlaceholder: 'Ej: Las vistas desde la torre del homenaje son espectaculares',
    externalUrlLabel: 'Comprar entradas',
    externalUrlPlaceholder: 'https://...',
    tags: ['gratis', 'entrada_de_pago', 'vistas', 'visita_guiada', 'patrimonio_unesco', 'historia'],
  },
  {
    id: 'palace',
    label: 'Palacio',
    icon: 'Crown',
    group: 'heritage',
    source: 'GOOGLE',
    radius: 10000,
    maxResults: 4,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Los 4 palacios y edificios históricos más importantes de {city}.',
    fetchDetails: true,
    highlightLabel: 'No te pierdas',
    highlightPlaceholder: 'Ej: Los jardines del ala este y la sala del trono',
    externalUrlLabel: 'Comprar entradas',
    externalUrlPlaceholder: 'https://...',
    tags: ['entrada_de_pago', 'visita_guiada', 'audioguía', 'patrimonio_unesco', 'jardines'],
  },
  {
    id: 'ruins',
    label: 'Ruinas / yacimiento arqueológico',
    icon: 'Columns',
    group: 'heritage',
    source: 'GOOGLE',
    radius: 15000,
    maxResults: 4,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Los 4 yacimientos arqueológicos y ruinas más importantes cerca de {city}.',
    fetchDetails: true,
    highlightLabel: 'No te pierdas',
    highlightPlaceholder: 'Ej: El mosaico del siglo II en la sala principal',
    externalUrlLabel: 'Comprar entradas',
    externalUrlPlaceholder: 'https://...',
    tags: ['gratis', 'entrada_de_pago', 'visita_guiada', 'patrimonio_unesco', 'historia'],
  },
  {
    id: 'monument',
    label: 'Monumento / estatua',
    icon: 'Landmark',
    group: 'heritage',
    source: 'GOOGLE',
    radius: 10000,
    maxResults: 5,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Los 5 monumentos, estatuas y esculturas más emblemáticos de {city}.',
    fetchDetails: true,
    highlightLabel: 'Curiosidad / historia',
    highlightPlaceholder: 'Ej: Se construyó en 1892 para conmemorar el centenario',
    tags: ['gratis', 'foto_icónica', 'instagram', 'historia'],
  },
  {
    id: 'historic_bridge',
    label: 'Puente histórico',
    icon: 'Milestone',
    group: 'heritage',
    source: 'GOOGLE',
    radius: 10000,
    maxResults: 3,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Los 3 puentes más históricos y fotogénicos de {city}.',
    fetchDetails: true,
    highlightLabel: 'Tip / curiosidad',
    highlightPlaceholder: 'Ej: Cruza al anochecer, las luces lo hacen increíble',
    tags: ['gratis', 'foto_icónica', 'instagram', 'historia', 'vistas'],
  },

  // ═══════════════════════════════════════════
  // 🎨 CULTURA & ARTE
  // ═══════════════════════════════════════════
  {
    id: 'museum',
    label: 'Museo',
    icon: 'Museum',
    group: 'culture',
    source: 'GOOGLE',
    radius: 10000,
    maxResults: 6,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Los 6 mejores museos de {city}. Incluye museos de historia, arte, ciencia y cultura local.',
    fetchDetails: true,
    highlightLabel: 'Colección / sala estrella',
    highlightPlaceholder: 'Ej: La colección de arte rupestre y la sala de escultura ibérica',
    externalUrlLabel: 'Comprar entradas',
    externalUrlPlaceholder: 'https://...',
    tags: ['gratis', 'entrada_de_pago', 'gratis_domingos', 'audioguía', 'visita_guiada', 'para_niños', 'accesible'],
  },
  {
    id: 'art_gallery',
    label: 'Galería de arte',
    icon: 'Palette',
    group: 'culture',
    source: 'GOOGLE',
    radius: 5000,
    maxResults: 4,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Las 4 mejores galerías de arte contemporáneo y moderno de {city}.',
    fetchDetails: true,
    highlightLabel: 'Artista / exposición destacada',
    highlightPlaceholder: 'Ej: Exposición permanente de artistas valencianos del siglo XX',
    externalUrlLabel: 'Web / entradas',
    externalUrlPlaceholder: 'https://...',
    tags: ['gratis', 'entrada_de_pago', 'visita_guiada', 'arte_contemporáneo'],
  },
  {
    id: 'theater',
    label: 'Teatro / ópera',
    icon: 'Drama',
    group: 'culture',
    source: 'GOOGLE',
    radius: 5000,
    maxResults: 3,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Los 3 teatros y salas de ópera más importantes de {city}.',
    fetchDetails: true,
    highlightLabel: 'Espectáculo recomendado',
    highlightPlaceholder: 'Ej: La temporada de zarzuela de octubre a mayo',
    externalUrlLabel: 'Comprar entradas',
    externalUrlPlaceholder: 'https://...',
    tags: ['visita_arquitectónica', 'dress_code', 'reserva_recomendada'],
  },
  {
    id: 'cultural_center',
    label: 'Centro cultural',
    icon: 'Building',
    group: 'culture',
    source: 'GOOGLE',
    radius: 5000,
    maxResults: 3,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Los 3 principales centros culturales, fundaciones y espacios de arte de {city}.',
    fetchDetails: true,
    highlightLabel: 'Qué tiene / no te pierdas',
    highlightPlaceholder: 'Ej: La biblioteca pública gratuita en la planta baja y el café',
    externalUrlLabel: 'Agenda / programación',
    externalUrlPlaceholder: 'https://...',
    tags: ['gratis', 'biblioteca', 'exposiciones', 'talleres', 'para_niños'],
  },

  // ═══════════════════════════════════════════
  // 🌿 NATURALEZA
  // ═══════════════════════════════════════════
  {
    id: 'park',
    label: 'Parque / jardín',
    icon: 'TreePine',
    group: 'nature',
    source: 'GOOGLE',
    radius: 5000,
    maxResults: 5,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Los 5 mejores parques y jardines de {city} para pasear, hacer deporte o descansar.',
    fetchDetails: true,
    highlightLabel: 'Mejor zona / tip',
    highlightPlaceholder: 'Ej: El lago del fondo tiene barcas de alquiler los fines de semana',
    tags: ['gratis', 'dog_friendly', 'deporte', 'picnic', 'accesible', 'jardín_histórico'],
  },
  {
    id: 'beach',
    label: 'Playa',
    icon: 'Waves',
    group: 'nature',
    source: 'GOOGLE',
    radius: 50000,
    maxResults: 6,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Las 6 mejores playas cerca de {city} (hasta 1h en coche). Mezcla playas populares, calas escondidas y playas familiares.',
    fetchDetails: true,
    highlightLabel: 'Mejor zona / tip',
    highlightPlaceholder: 'Ej: La zona norte tiene menos gente, llega antes de las 10h en verano',
    tags: ['bandera_azul', 'cala_escondida', 'agua_cristalina', 'chiringuito', 'deportes_acuáticos', 'nudismo', 'dog_friendly', 'aparcamiento_fácil', 'accesible'],
  },
  {
    id: 'cove',
    label: 'Cala / playa escondida',
    icon: 'Anchor',
    group: 'nature',
    source: 'GOOGLE',
    radius: 30000,
    maxResults: 5,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Las 5 calas más bonitas y escondidas cerca de {city}.',
    fetchDetails: true,
    highlightLabel: 'Cómo llegar / tip',
    highlightPlaceholder: 'Ej: 15 min a pie desde el parking de Cap Negret, lleva agua',
    tags: ['agua_cristalina', 'snorkel', 'solo_a_pie', 'poco_conocida', 'nudismo'],
  },
  {
    id: 'river_lake',
    label: 'Río / lago / embalse',
    icon: 'Droplets',
    group: 'nature',
    source: 'GOOGLE',
    radius: 30000,
    maxResults: 4,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Los 4 ríos, lagos y embalses más bonitos o visitados cerca de {city}.',
    fetchDetails: true,
    highlightLabel: 'Actividad / tip',
    highlightPlaceholder: 'Ej: Kayak de alquiler en la orilla este, 10€/hora',
    tags: ['kayak', 'pesca', 'baño', 'senderismo', 'gratis', 'dog_friendly'],
  },
  {
    id: 'viewpoint',
    label: 'Mirador',
    icon: 'Mountain',
    group: 'nature',
    source: 'GOOGLE',
    radius: 20000,
    maxResults: 5,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Los 5 mejores miradores con vistas de {city} y alrededores.',
    fetchDetails: true,
    highlightLabel: 'Mejor momento',
    highlightPlaceholder: 'Ej: Al atardecer, orientado al oeste, impresionante',
    tags: ['puesta_de_sol', 'amanecer', 'instagram', 'gratis', 'acceso_en_coche', 'solo_a_pie'],
  },
  {
    id: 'hiking',
    label: 'Senderismo / montaña',
    icon: 'Footprints',
    group: 'nature',
    source: 'GOOGLE',
    radius: 30000,
    maxResults: 5,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Las 5 mejores rutas de senderismo y zonas de montaña cerca de {city}. Incluye rutas fáciles y moderadas.',
    fetchDetails: true,
    highlightLabel: 'Dificultad / tip',
    highlightPlaceholder: 'Ej: Ruta circular 8km, nivel medio. Lleva agua y calzado de trekking',
    externalUrlLabel: 'Mapa / Wikiloc',
    externalUrlPlaceholder: 'https://es.wikiloc.com/...',
    tags: ['nivel_fácil', 'nivel_medio', 'nivel_difícil', 'circular', 'con_niños', 'dog_friendly', 'vistas_panorámicas'],
  },
  {
    id: 'waterfall',
    label: 'Cascada',
    icon: 'Droplets',
    group: 'nature',
    source: 'GOOGLE',
    radius: 50000,
    maxResults: 3,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Las 3 cascadas y saltos de agua más espectaculares cerca de {city}.',
    fetchDetails: true,
    highlightLabel: 'Cómo llegar / mejor época',
    highlightPlaceholder: 'Ej: Mejor en primavera, acceso por la pista forestal desde Relleu',
    tags: ['solo_a_pie', 'baño', 'nivel_fácil', 'nivel_medio', 'con_niños'],
  },
  {
    id: 'cave',
    label: 'Cueva / gruta',
    icon: 'Triangle',
    group: 'nature',
    source: 'GOOGLE',
    radius: 50000,
    maxResults: 3,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Las 3 cuevas y grutas más espectaculares o visitadas cerca de {city}.',
    fetchDetails: true,
    highlightLabel: 'No te pierdas',
    highlightPlaceholder: 'Ej: La sala de las estalactitas es impresionante, lleva jersey',
    externalUrlLabel: 'Comprar entradas',
    externalUrlPlaceholder: 'https://...',
    tags: ['entrada_de_pago', 'visita_guiada', 'temperatura_fresca', 'con_niños'],
  },
  {
    id: 'natural_park',
    label: 'Parque natural / reserva',
    icon: 'TreeDeciduous',
    group: 'nature',
    source: 'GOOGLE',
    radius: 100000,
    maxResults: 3,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Los 3 parques naturales y reservas más importantes cerca de {city}.',
    fetchDetails: true,
    highlightLabel: 'Actividad / qué ver',
    highlightPlaceholder: 'Ej: Avistamiento de flamencos en la laguna sur, mejor en otoño',
    externalUrlLabel: 'Web del parque',
    externalUrlPlaceholder: 'https://...',
    tags: ['reserva_previa', 'senderismo', 'birdwatching', 'wildlife', 'gratuito'],
  },

  // ═══════════════════════════════════════════
  // 🏙️ VIDA URBANA
  // ═══════════════════════════════════════════
  {
    id: 'square',
    label: 'Plaza',
    icon: 'MapPin',
    group: 'urban',
    source: 'GOOGLE',
    radius: 5000,
    maxResults: 5,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Las 5 plazas más emblemáticas, animadas y bonitas de {city}.',
    fetchDetails: true,
    highlightLabel: 'Qué pasa aquí',
    highlightPlaceholder: 'Ej: Mercado de navidad en diciembre, mercadillo los domingos',
    tags: ['gratis', 'mercado', 'terraza', 'instagram', 'animado', 'histórico'],
  },
  {
    id: 'market',
    label: 'Mercado tradicional',
    icon: 'ShoppingBasket',
    group: 'urban',
    source: 'GOOGLE',
    radius: 5000,
    maxResults: 4,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Los 4 mejores mercados tradicionales, mercados de abastos y mercadillos de {city}.',
    fetchDetails: true,
    highlightLabel: 'Qué comprar / horario',
    highlightPlaceholder: 'Ej: Mañanas, llega antes de las 10. Compra el queso curado del puesto 34',
    tags: ['productos_locales', 'mercadillo', 'antigüedades', 'gastronomía', 'gratis'],
  },
  {
    id: 'neighborhood',
    label: 'Barrio con encanto',
    icon: 'Home',
    group: 'urban',
    source: 'GOOGLE',
    radius: 5000,
    maxResults: 4,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Los 4 barrios más interesantes, auténticos y con encanto de {city} para pasear.',
    fetchDetails: true,
    highlightLabel: 'Qué ver / ambiente',
    highlightPlaceholder: 'Ej: Pasea por las calles del centro histórico al atardecer, lleno de gente',
    tags: ['paseo', 'instagram', 'gastronomía', 'tiendas_locales', 'gratis', 'historia'],
  },
  {
    id: 'promenade',
    label: 'Paseo / rambla / malecón',
    icon: 'Footprints',
    group: 'urban',
    source: 'GOOGLE',
    radius: 5000,
    maxResults: 3,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Los 3 mejores paseos marítimos, ramblas y paseos urbanos de {city}.',
    fetchDetails: true,
    highlightLabel: 'Mejor momento',
    highlightPlaceholder: 'Ej: Al atardecer, impresionante la luz en el puerto',
    tags: ['gratis', 'instagram', 'accesible', 'dog_friendly', 'deporte'],
  },
  {
    id: 'port',
    label: 'Puerto / marina',
    icon: 'Anchor',
    group: 'urban',
    source: 'GOOGLE',
    radius: 10000,
    maxResults: 3,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'El puerto, marina y zona portuaria más interesante de {city}.',
    fetchDetails: true,
    highlightLabel: 'Qué hacer aquí',
    highlightPlaceholder: 'Ej: Alquiler de barcos, el mercado de pescado de la mañana',
    tags: ['gratis', 'restaurantes', 'barcos', 'instagram', 'sunset'],
  },

  // ═══════════════════════════════════════════
  // 🎯 ACTIVIDADES
  // ═══════════════════════════════════════════
  {
    id: 'water_sports',
    label: 'Deportes acuáticos',
    icon: 'Sailboat',
    group: 'activities',
    source: 'GOOGLE',
    radius: 20000,
    maxResults: 5,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Las 5 mejores empresas y lugares para deportes acuáticos en {city}: kayak, paddle surf, buceo, snorkel, jet ski.',
    fetchDetails: true,
    highlightLabel: 'Actividad / precio',
    highlightPlaceholder: 'Ej: Kayak de alquiler desde 10€/h, también excursiones guiadas',
    externalUrlLabel: 'Reservar actividad',
    externalUrlPlaceholder: 'https://...',
    tags: ['kayak', 'paddle_surf', 'buceo', 'snorkel', 'jet_ski', 'vela', 'para_niños', 'reserva_previa'],
  },
  {
    id: 'cycling',
    label: 'Ciclismo / bicicleta',
    icon: 'Bike',
    group: 'activities',
    source: 'GOOGLE',
    radius: 15000,
    maxResults: 4,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Los 4 mejores alquileres de bicicletas y rutas ciclistas de {city}.',
    fetchDetails: true,
    highlightLabel: 'Ruta / tip',
    highlightPlaceholder: 'Ej: Ruta del litoral, 20km sin cuestas, impresionante',
    externalUrlLabel: 'Reservar / Wikiloc',
    externalUrlPlaceholder: 'https://...',
    tags: ['alquiler', 'ruta_fácil', 'ruta_montaña', 'ebike', 'para_niños'],
  },
  {
    id: 'spa',
    label: 'Spa / bienestar',
    icon: 'Sparkles',
    group: 'activities',
    source: 'GOOGLE',
    radius: 10000,
    maxResults: 4,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Los 4 mejores spas, centros de bienestar y balnearios de {city}.',
    fetchDetails: true,
    highlightLabel: 'Tratamiento estrella',
    highlightPlaceholder: 'Ej: El circuito de aguas + masaje de 60 min, oferta entre semana',
    externalUrlLabel: 'Reservar',
    externalUrlPlaceholder: 'https://...',
    tags: ['romántico', 'parejas', 'reserva_previa', 'económico', 'hammam'],
  },
  {
    id: 'adventure',
    label: 'Aventura / adrenalina',
    icon: 'Zap',
    group: 'activities',
    source: 'GOOGLE',
    radius: 30000,
    maxResults: 4,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Las 4 mejores actividades de aventura cerca de {city}: escalada, tirolina, quads, barranquismo.',
    fetchDetails: true,
    highlightLabel: 'Actividad / precio',
    highlightPlaceholder: 'Ej: Tirolina de 200m sobre el río, desde 25€ con monitor',
    externalUrlLabel: 'Reservar actividad',
    externalUrlPlaceholder: 'https://...',
    tags: ['escalada', 'barranquismo', 'quads', 'tirolina', 'para_grupos', 'para_niños', 'reserva_previa'],
  },
  {
    id: 'boat_trip',
    label: 'Excursión en barco',
    icon: 'Ship',
    group: 'activities',
    source: 'GOOGLE',
    radius: 20000,
    maxResults: 4,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Las 4 mejores excursiones en barco y paseos marítimos desde {city}.',
    fetchDetails: true,
    highlightLabel: 'Excursión / duración',
    highlightPlaceholder: 'Ej: Ruta de cuevas marinas 3h, incluye snorkel y bebida',
    externalUrlLabel: 'Reservar',
    externalUrlPlaceholder: 'https://...',
    tags: ['con_niños', 'snorkel', 'puesta_de_sol', 'reserva_previa', 'privado'],
  },
  {
    id: 'golf',
    label: 'Golf',
    icon: 'CircleDot',
    group: 'activities',
    source: 'GOOGLE',
    radius: 30000,
    maxResults: 4,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Los 4 mejores campos de golf cerca de {city}.',
    fetchDetails: true,
    highlightLabel: 'Tip / dificultad',
    highlightPlaceholder: 'Ej: Campo de 18 hoyos, nivel medio-alto, se requiere handicap',
    externalUrlLabel: 'Reservar green fee',
    externalUrlPlaceholder: 'https://...',
    tags: ['18_hoyos', '9_hoyos', 'vistas_al_mar', 'academia', 'alquiler_palos'],
  },

  // ═══════════════════════════════════════════
  // 🛍️ COMPRAS
  // ═══════════════════════════════════════════
  {
    id: 'shopping_mall',
    label: 'Centro comercial',
    icon: 'ShoppingBag',
    group: 'shopping',
    source: 'GOOGLE',
    radius: 15000,
    maxResults: 4,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Los 4 mejores centros comerciales de {city} y alrededores.',
    fetchDetails: true,
    highlightLabel: 'Tiendas destacadas / tip',
    highlightPlaceholder: 'Ej: El Corte Inglés más grande de la provincia, parking gratuito 2h',
    externalUrlLabel: 'Web / directorio',
    externalUrlPlaceholder: 'https://...',
    tags: ['parking_gratuito', 'cine', 'restauración', 'outlet', 'marcas_internacionales'],
  },
  {
    id: 'outlet',
    label: 'Outlet / descuentos',
    icon: 'Tag',
    group: 'shopping',
    source: 'GOOGLE',
    radius: 30000,
    maxResults: 3,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Los 3 mejores outlets y centros de descuentos cerca de {city}.',
    fetchDetails: true,
    highlightLabel: 'Marcas / descuento',
    highlightPlaceholder: 'Ej: Hasta 70% en Nike, Adidas y marcas de lujo',
    externalUrlLabel: 'Web',
    externalUrlPlaceholder: 'https://...',
    tags: ['marcas_internacionales', 'temporada', 'parking_gratuito'],
  },
  {
    id: 'local_shops',
    label: 'Tiendas locales / boutiques',
    icon: 'Store',
    group: 'shopping',
    source: 'GOOGLE',
    radius: 5000,
    maxResults: 5,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Las 5 mejores tiendas locales, boutiques y comercios con encanto de {city}.',
    fetchDetails: true,
    highlightLabel: 'Qué encontrar',
    highlightPlaceholder: 'Ej: Cerámica artesanal local, solo pagos en efectivo',
    tags: ['artesanal', 'local', 'souvenir', 'antigüedades', 'moda_independiente'],
  },
  {
    id: 'craft_market',
    label: 'Mercado artesanal / feria',
    icon: 'Brush',
    group: 'shopping',
    source: 'GOOGLE',
    radius: 5000,
    maxResults: 4,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Los 4 mejores mercados artesanales, ferias y mercadillos de {city}.',
    fetchDetails: true,
    highlightLabel: 'Días / horario',
    highlightPlaceholder: 'Ej: Solo sábados y domingos de 10:00 a 14:00',
    tags: ['artesanal', 'antigüedades', 'gratis', 'fin_de_semana'],
  },

  // ═══════════════════════════════════════════
  // 👨‍👩‍👧 FAMILIA
  // ═══════════════════════════════════════════
  {
    id: 'theme_park',
    label: 'Parque temático / de atracciones',
    icon: 'Ferris Wheel',
    group: 'family',
    source: 'GOOGLE',
    radius: 50000,
    maxResults: 3,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Los 3 mejores parques temáticos, de atracciones y acuáticos cerca de {city}.',
    fetchDetails: true,
    highlightLabel: 'Atracción estrella / tip',
    highlightPlaceholder: 'Ej: Compra entrada online, evita colas. La montaña rusa XL vale la pena',
    externalUrlLabel: 'Comprar entradas',
    externalUrlPlaceholder: 'https://...',
    tags: ['para_niños', 'acuático', 'reserva_previa', 'descuento_online', 'accesible'],
  },
  {
    id: 'zoo',
    label: 'Zoo / acuario / granja',
    icon: 'Rabbit',
    group: 'family',
    source: 'GOOGLE',
    radius: 30000,
    maxResults: 3,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Los 3 mejores zoos, acuarios y granjas escuela cerca de {city}.',
    fetchDetails: true,
    highlightLabel: 'Qué ver / especie estrella',
    highlightPlaceholder: 'Ej: Los shows de delfines a las 12h y 17h incluidos en la entrada',
    externalUrlLabel: 'Comprar entradas',
    externalUrlPlaceholder: 'https://...',
    tags: ['para_niños', 'accesible', 'reserva_previa', 'descuento_online'],
  },
  {
    id: 'kids_museum',
    label: 'Museo interactivo / para niños',
    icon: 'Lightbulb',
    group: 'family',
    source: 'GOOGLE',
    radius: 15000,
    maxResults: 3,
    defaultEnabled: false,
    searchMode: 'ai_curated',
    aiPrompt: 'Los 3 mejores museos interactivos, de ciencia y espacios educativos para niños en {city}.',
    fetchDetails: true,
    highlightLabel: 'Edad recomendada / tip',
    highlightPlaceholder: 'Ej: A partir de 5 años. La sala de experimentos es lo mejor',
    externalUrlLabel: 'Comprar entradas',
    externalUrlPlaceholder: 'https://...',
    tags: ['para_niños', 'educativo', 'accesible', 'gratis_menores_3'],
  },

  // ═══════════════════════════════════════════
  // 🔧 SERVICIOS (OSM, gratuito)
  // ═══════════════════════════════════════════
  {
    id: 'pharmacy',
    label: 'Farmacias',
    icon: 'Pill',
    group: 'services',
    source: 'OSM',
    radius: 2000,
    maxResults: 5,
    defaultEnabled: true,
    osmTags: { amenity: 'pharmacy' },
    fetchDetails: true,
  },
  {
    id: 'hospital',
    label: 'Hospitales y urgencias',
    icon: 'Hospital',
    group: 'services',
    source: 'OSM',
    radius: 5000,
    maxResults: 3,
    defaultEnabled: true,
    osmTags: { amenity: ['hospital', 'clinic'] },
  },
  {
    id: 'parking',
    label: 'Aparcamientos',
    icon: 'ParkingCircle',
    group: 'services',
    source: 'OSM',
    radius: 2000,
    maxResults: 5,
    defaultEnabled: true,
    osmTags: { amenity: 'parking' },
  },
  {
    id: 'supermarket',
    label: 'Supermercados',
    icon: 'ShoppingCart',
    group: 'services',
    source: 'OSM',
    radius: 1500,
    maxResults: 5,
    defaultEnabled: false,
    osmTags: { shop: 'supermarket' },
    fetchDetails: true,
  },
  {
    id: 'atm',
    label: 'Cajeros automáticos',
    icon: 'Banknote',
    group: 'services',
    source: 'OSM',
    radius: 1500,
    maxResults: 3,
    defaultEnabled: false,
    osmTags: { amenity: 'atm' },
  },
  {
    id: 'gas_station',
    label: 'Gasolineras',
    icon: 'Fuel',
    group: 'services',
    source: 'OSM',
    radius: 3000,
    maxResults: 3,
    defaultEnabled: false,
    osmTags: { amenity: 'fuel' },
  },
  {
    id: 'gym',
    label: 'Gimnasios',
    icon: 'Dumbbell',
    group: 'services',
    source: 'OSM',
    radius: 2000,
    maxResults: 3,
    defaultEnabled: false,
    osmTags: { leisure: 'fitness_centre' },
  },
  {
    id: 'laundry',
    label: 'Lavanderías',
    icon: 'WashingMachine',
    group: 'services',
    source: 'OSM',
    radius: 2000,
    maxResults: 3,
    defaultEnabled: false,
    osmTags: { shop: ['laundry', 'dry_cleaning'] },
  },
  {
    id: 'transit_station',
    label: 'Transporte público',
    icon: 'Train',
    group: 'services',
    source: 'OSM',
    radius: 1500,
    maxResults: 3,
    defaultEnabled: false,
    osmTags: { public_transport: 'station' },
  },
]

/** Average walking speed: 80 meters per minute (~4.8 km/h) */
export const WALK_SPEED_MPM = 80

/** Cache TTL: 30 days in milliseconds */
export const CACHE_TTL_MS = 30 * 24 * 60 * 60 * 1000

/** Geo-tile precision: 2 decimal places ≈ ~1.1km grid */
export const TILE_PRECISION = 100

export function getCategoryById(id: string): CategoryConfig | undefined {
  return CATEGORIES.find(c => c.id === id)
}

export function getCategoriesByGroup(groupId: string): CategoryConfig[] {
  return CATEGORIES.filter(c => c.group === groupId)
}

export function getCategoriesBySource(source: DataSource): CategoryConfig[] {
  return CATEGORIES.filter(c => c.source === source)
}

export function geoTileKey(lat: number, lng: number): string {
  return `${Math.round(lat * TILE_PRECISION)}:${Math.round(lng * TILE_PRECISION)}`
}
